packages:
  - "frontend"
  - "backend"
  - "packages/*"
  - "database"

allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
  workerd: true

onlyBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver
  - workerd

settings:
  confirmModulesPurge: false
