// Mapeo semántico de intenciones → IDs del manifiesto de Mero.
// Las escenas representan intenciones, no pantallas.
// Una misma escena puede reutilizarse en Home, Onboarding, Ruta, etc.
//
// USO: <MeroScene id={MERO_SCENES.welcome} />
// NUNCA: <MeroScene id="bienvenido" /> ni <Image src="/mero/..." />

export const MERO_SCENES = {
  // ── Presencia y emoción ──────────────────────────────────────────
  welcome:              "bienvenido",
  greeting:             "saludando",
  happy:                "feliz",
  celebrating:          "celebrando",
  success:              "muy-bien",
  encouragement:        "vamos",
  wellDone:             "bien-hecho",
  excellent:            "excelente",
  handOnChest:          "mano-en-el-pecho",
  armsOpen:             "brazos-abiertos",
  inviting:             "invitando-a-continuar",
  keepGoing:            "sigue",
  almostThere:          "casi",
  confetti:             "confeti",
  fireworks:            "fuegos-artificiales",
  clapping:             "aplaudiendo",
  listening:            "escuchando",
  havingCoffee:         "tomando-cafe",

  // ── Gestos ───────────────────────────────────────────────────────
  thumbsUp:             "pulgar-arriba",
  pointingUp:           "senalando-arriba",
  pointingDown:         "senalando-abajo",
  pointingRight:        "senalando-derecha",
  showingExample:       "mostrando-un-ejemplo",
  showingResults:       "mostrando-resultados",

  // ── Estudio ──────────────────────────────────────────────────────
  thinking:             "pensando",
  explaining:           "explicando",
  reading:              "leyendo",
  studying:             "estudiando-en-escritorio",
  writing:              "escribiendo",
  stepByStep:           "explicando-paso-a-paso",
  takingNotes:          "tomando-notas",
  analyzing:            "analizando",
  flashcards:           "haciendo-flashcards",
  solvingQuestions:     "resolviendo-preguntas",
  teaching:             "ensenando",
  searching:            "buscando-informacion",
  readingDoc:           "leer",
  readingBook:          "leyendo-un-libro",
  comparing:            "comparando-opciones",
  watchingScreen:       "mirando-una-pantalla",
  highlighting:         "con-un-resaltador",
  usingComputer:        "con-computador",
  usingLaptop:          "con-un-portatil",
  usingTablet:          "con-una-tablet",

  // ── Simulacros y práctica ────────────────────────────────────────
  correct:              "marcando-correcta",
  incorrect:            "marcando-incorrecta",
  completed:            "completado",
  timeWarning:          "tiempo-agotandose",
  submitting:           "entregando-examen",
  reviewingExam:        "revisando-examen",
  answering:            "respondiendo",
  correcting:           "corrigiendo-respuestas",
  reviewingRules:       "revisando-normas",
  timer:                "cronometro",
  holdingTimer:         "con-cronometro",

  // ── Logros y gamificación ────────────────────────────────────────
  streak:               "racha",
  levelUp:              "nivel-nuevo",
  trophy:               "trofeo",
  medal:                "medalla",
  achievement:          "nuevo-logro",
  diamond:              "diamante",
  star:                 "estrella",
  badge:                "insignia",
  celebratingApproval:  "celebrando-aprobacion",
  goalReached:          "meta-alcanzada",
  goalCompleted:        "meta-cumplida",

  // ── Estados vacíos y error ───────────────────────────────────────
  error:                "intentalo-otra-vez",
  dontGiveUp:           "no-te-rindas",
  tryAgain:             "intentalo-otra-vez",
  noConnection:         "sin-conexion",
  noData:               "sin-datos",
  notFound:             "no-encontrado",
  showingError:         "error",
  saved:                "guardado",
  savingCopy:           "guardar-copia",
  updating:             "actualizando",

  // ── Cargos ───────────────────────────────────────────────────────
  withLabCoat:          "con-bata",
  withHelmet:           "con-casco",
  withGown:             "con-toga",
  withSuit:             "con-traje-ejecutivo",
  withFolder:           "con-carpeta",
  withBriefcase:        "con-maletin",
  withDocuments:        "con-documentos",
  withOfficialDocs:     "con-documentos-oficiales",
  withMagnifier:        "con-lupa",
  withDianUniform:      "con-uniforme-dian",
  withPoliceUniform:    "con-uniforme-policia",
} as const;

export type MeroSceneName = keyof typeof MERO_SCENES;

// Registro de variantes — preparado para selección futura (aleatoria o contextual).
// El índice [0] siempre coincide con el valor en MERO_SCENES (el default actual).
// La lógica de selección NO está implementada todavía.
export const MERO_SCENE_VARIANTS: Readonly<Record<MeroSceneName, readonly string[]>> = {
  welcome:              ["bienvenido", "saludando"],
  greeting:             ["saludando", "bienvenido"],
  happy:                ["feliz", "muy-bien"],
  celebrating:          ["celebrando", "racha", "nivel-nuevo"],
  success:              ["muy-bien", "celebrando", "pulgar-arriba"],
  encouragement:        ["vamos", "no-te-rindas"],
  wellDone:             ["bien-hecho", "muy-bien"],
  excellent:            ["excelente", "celebrando"],
  handOnChest:          ["mano-en-el-pecho"],
  armsOpen:             ["brazos-abiertos", "bienvenido"],
  inviting:             ["invitando-a-continuar", "vamos"],
  keepGoing:            ["sigue", "vamos"],
  almostThere:          ["casi", "vamos"],
  confetti:             ["confeti", "celebrando"],
  fireworks:            ["fuegos-artificiales", "celebrando"],
  clapping:             ["aplaudiendo", "celebrando"],
  listening:            ["escuchando"],
  havingCoffee:         ["tomando-cafe"],
  thumbsUp:             ["pulgar-arriba"],
  pointingUp:           ["senalando-arriba"],
  pointingDown:         ["senalando-abajo"],
  pointingRight:        ["senalando-derecha"],
  showingExample:       ["mostrando-un-ejemplo"],
  showingResults:       ["mostrando-resultados"],
  thinking:             ["pensando"],
  explaining:           ["explicando", "explicando-paso-a-paso"],
  reading:              ["leyendo", "leyendo-un-libro", "leer"],
  studying:             ["estudiando-en-escritorio", "leyendo", "escribiendo"],
  writing:              ["escribiendo", "tomando-notas"],
  stepByStep:           ["explicando-paso-a-paso", "explicando"],
  takingNotes:          ["tomando-notas", "escribiendo"],
  analyzing:            ["analizando", "pensando"],
  flashcards:           ["haciendo-flashcards"],
  solvingQuestions:     ["resolviendo-preguntas"],
  teaching:             ["ensenando", "explicando"],
  searching:            ["buscando-informacion"],
  readingDoc:           ["leer", "leyendo"],
  readingBook:          ["leyendo-un-libro", "leyendo"],
  comparing:            ["comparando-opciones"],
  watchingScreen:       ["mirando-una-pantalla"],
  highlighting:         ["con-un-resaltador"],
  usingComputer:        ["con-computador", "con-un-portatil"],
  usingLaptop:          ["con-un-portatil", "con-computador"],
  usingTablet:          ["con-una-tablet"],
  correct:              ["marcando-correcta", "pulgar-arriba"],
  incorrect:            ["marcando-incorrecta"],
  completed:            ["completado"],
  timeWarning:          ["tiempo-agotandose"],
  submitting:           ["entregando-examen"],
  reviewingExam:        ["revisando-examen"],
  answering:            ["respondiendo"],
  correcting:           ["corrigiendo-respuestas"],
  reviewingRules:       ["revisando-normas"],
  timer:                ["cronometro"],
  holdingTimer:         ["con-cronometro", "cronometro"],
  streak:               ["racha"],
  levelUp:              ["nivel-nuevo"],
  trophy:               ["trofeo"],
  medal:                ["medalla"],
  achievement:          ["nuevo-logro", "trofeo", "medalla"],
  diamond:              ["diamante"],
  star:                 ["estrella"],
  badge:                ["insignia"],
  celebratingApproval:  ["celebrando-aprobacion", "celebrando"],
  goalReached:          ["meta-alcanzada"],
  goalCompleted:        ["meta-cumplida", "meta-alcanzada"],
  error:                ["intentalo-otra-vez", "no-te-rindas"],
  dontGiveUp:           ["no-te-rindas"],
  tryAgain:             ["intentalo-otra-vez"],
  noConnection:         ["sin-conexion"],
  noData:               ["sin-datos"],
  notFound:             ["no-encontrado"],
  showingError:         ["error", "intentalo-otra-vez"],
  saved:                ["guardado"],
  savingCopy:           ["guardar-copia"],
  updating:             ["actualizando"],
  withLabCoat:          ["con-bata"],
  withHelmet:           ["con-casco"],
  withGown:             ["con-toga"],
  withSuit:             ["con-traje-ejecutivo"],
  withFolder:           ["con-carpeta"],
  withBriefcase:        ["con-maletin"],
  withDocuments:        ["con-documentos"],
  withOfficialDocs:     ["con-documentos-oficiales"],
  withMagnifier:        ["con-lupa"],
  withDianUniform:      ["con-uniforme-dian"],
  withPoliceUniform:    ["con-uniforme-policia"],
};
